Add de-query-tool
HEPCloud/decisionengine pull request #332
Opened 2021-04-22 20:41 UTC by BrunoCoimbra

This addresses issue #111 requested by @StevenCTimm.

The new **de-query-tool** fetches all generations of a product from one or more recent task managers.
I made some changes to the PostgreSQL datasoruce to make it possible to query data products by name.

2021-04-22 20:41 UTC, pep8speaks commented
Hello @BrunoCoimbra! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:









* In the file [`src/decisionengine/framework/engine/DecisionEngine.py`](https://github.com/HEPCloud/decisionengine/blob/ab19261036361d787a3e015cbe75c1c571137864/src/decisionengine/framework/engine/DecisionEngine.py):

> [Line 108:1](https://github.com/HEPCloud/decisionengine/blob/ab19261036361d787a3e015cbe75c1c571137864/src/decisionengine/framework/engine/DecisionEngine.py#L108): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 480:57](https://github.com/HEPCloud/decisionengine/blob/ab19261036361d787a3e015cbe75c1c571137864/src/decisionengine/framework/engine/DecisionEngine.py#L480): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 481:57](https://github.com/HEPCloud/decisionengine/blob/ab19261036361d787a3e015cbe75c1c571137864/src/decisionengine/framework/engine/DecisionEngine.py#L481): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 482:57](https://github.com/HEPCloud/decisionengine/blob/ab19261036361d787a3e015cbe75c1c571137864/src/decisionengine/framework/engine/DecisionEngine.py#L482): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent

* In the file [`src/decisionengine/framework/engine/de_query_tool.py`](https://github.com/HEPCloud/decisionengine/blob/ab19261036361d787a3e015cbe75c1c571137864/src/decisionengine/framework/engine/de_query_tool.py):

> [Line 19:55](https://github.com/HEPCloud/decisionengine/blob/ab19261036361d787a3e015cbe75c1c571137864/src/decisionengine/framework/engine/de_query_tool.py#L19): [E502](https://duckduckgo.com/?q=pep8%20E502) the backslash is redundant between brackets
> [Line 20:70](https://github.com/HEPCloud/decisionengine/blob/ab19261036361d787a3e015cbe75c1c571137864/src/decisionengine/framework/engine/de_query_tool.py#L20): [E502](https://duckduckgo.com/?q=pep8%20E502) the backslash is redundant between brackets
> [Line 65:1](https://github.com/HEPCloud/decisionengine/blob/ab19261036361d787a3e015cbe75c1c571137864/src/decisionengine/framework/engine/de_query_tool.py#L65): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1

2021-04-22 21:03 UTC, jcpunk commented
CodeCov is reporting a lot of missed lines on this (see the comments on the "files changed" tab)

2021-05-07 17:30 UTC, mambelli commented
In  src/decisionengine/framework/tests/test_query_tool_server.py there are 2 functions w/ the same name. Then more lines should be covered by tests. On the exception you can add the pragma to skip the coverage test.

2021-05-14 20:59 UTC, mambelli requested changes
For this time can be OK but whenever changing a docstring it should be changed to our standard Google format. 
There are 2 comments to add the pragmas to skip for coverage counting.

2021-05-14 20:59 UTC, mambelli commented on src/decisionengine/framework/engine/DecisionEngine.py
> +                    except Exception as e:
Can add pragma not to count in coverage

2021-05-14 20:59 UTC, mambelli commented on src/decisionengine/framework/engine/de_query_tool.py
> +    except Exception as e:
Pragma for coverage should go to all generic exceptions

2021-05-18 16:25 UTC, mambelli approved these changes

2021-05-18 16:26 UTC, merged