Fixed bugs in metrics with labels
HEPCloud/decisionengine pull request #701
Opened 2024-02-02 17:08 UTC by IlyaBaburashvili

Removed decorators in metrics with labels and moved timing inside function.

2024-02-02 17:08 UTC, pep8speaks commented
Hello @IlyaBaburashvili! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`src/decisionengine/framework/engine/DecisionEngine.py`](https://github.com/HEPCloud/decisionengine/blob/65ba08a64265b629dc5ce02541daccc7bb0cf9b2/src/decisionengine/framework/engine/DecisionEngine.py):

> [Line 996:13](https://github.com/HEPCloud/decisionengine/blob/65ba08a64265b629dc5ce02541daccc7bb0cf9b2/src/decisionengine/framework/engine/DecisionEngine.py#L996): [E116](https://duckduckgo.com/?q=pep8%20E116) unexpected indentation (comment)
> [Line 1086:73](https://github.com/HEPCloud/decisionengine/blob/65ba08a64265b629dc5ce02541daccc7bb0cf9b2/src/decisionengine/framework/engine/DecisionEngine.py#L1086): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2024-02-02 22:41 UTC, vitodb commented
With this PR now unit tests are happy.
Tests for the PR were successful on Jenkins and also running unit tests interactively all tests went through. Any test got stuck.

2024-02-15 15:59 UTC, mambelli approved these changes

2024-02-15 16:00 UTC, mambelli requested changes
Can you rebase from master please?

2024-02-16 16:47 UTC, mambelli approved these changes

2024-02-16 16:49 UTC, merged